name: Lint DotNet
on:
  workflow_dispatch: {}
  # Disabled because the 8.x format is unreliable with source generators
  # pull_request:
  #   types: [edited, opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/parts/cache/
      - name: 'Run dotnet checks'
        run: |
          dotnet format --verify-no-changes
